import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { applyPatch, type Operation as JsonPatchOperation } from "fast-json-patch";
import openapiTS, { astToString } from "openapi-typescript";

const HTTP_METHODS = ["get", "post", "put", "patch", "delete", "head", "options"] as const;

interface OpenAPIOperation {
  readonly operationId?: string;
  readonly deprecated?: boolean;
}

interface OpenAPIDocument {
  readonly paths?: Readonly<Record<string, Readonly<Record<string, OpenAPIOperation>>>>;
}

export interface GenerateFromOpenAPIOptions {
  readonly specPath: string;
  readonly patchDir?: string;
  readonly outputDir: string;
  readonly packageImport?: string;
  readonly skipDeprecated?: boolean;
}

const identifier = (value: string): string => {
  const normalized = value.replaceAll(/[^A-Za-z0-9_$]+(.)?/g, (_match, next: string | undefined) =>
    next ? next.toUpperCase() : "",
  );
  const safe = normalized.length === 0 ? "operation" : normalized;
  return /^[A-Za-z_$]/.test(safe) ? safe : `_${safe}`;
};

const pascal = (value: string): string => {
  const safe = identifier(value);
  return safe.charAt(0).toUpperCase() + safe.slice(1);
};

const loadPatchedSpec = async (
  specPath: string,
  patchDir?: string,
): Promise<OpenAPIDocument> => {
  let spec = JSON.parse(await readFile(specPath, "utf8")) as OpenAPIDocument;
  if (!patchDir) return spec;
  let entries: string[];
  try {
    entries = await readdir(patchDir);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return spec;
    throw error;
  }
  for (const entry of entries.filter((name) => name.endsWith(".patch.json")).sort()) {
    const patch = JSON.parse(await readFile(join(patchDir, entry), "utf8")) as JsonPatchOperation[];
    spec = applyPatch(structuredClone(spec), patch, true, false).newDocument as OpenAPIDocument;
  }
  return spec;
};

export const generateFromOpenAPI = async (
  options: GenerateFromOpenAPIOptions,
): Promise<{ readonly operationCount: number }> => {
  const packageImport = options.packageImport ?? "@kevinmichaelchen/distilled";
  const spec = await loadPatchedSpec(options.specPath, options.patchDir);
  const operations: Array<{ operationId: string; method: string; path: string }> = [];
  const seen = new Set<string>();

  for (const [path, pathItem] of Object.entries(spec.paths ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (!operation?.operationId) continue;
      if (options.skipDeprecated && operation.deprecated) continue;
      if (seen.has(operation.operationId)) {
        throw new Error(`Duplicate operationId: ${operation.operationId}`);
      }
      seen.add(operation.operationId);
      operations.push({ operationId: operation.operationId, method: method.toUpperCase(), path });
    }
  }

  await rm(options.outputDir, { recursive: true, force: true });
  await mkdir(join(options.outputDir, "operations"), { recursive: true });

  const typeAst = await openapiTS(spec as never, { alphabetize: true });
  await writeFile(
    join(options.outputDir, "openapi.ts"),
    `// Generated by @kevinmichaelchen/distilled. DO NOT EDIT.\n${astToString(typeAst)}`,
  );

  const exports: string[] = [];
  const manifest: Array<Record<string, string>> = [];
  for (const operation of operations) {
    const functionName = identifier(operation.operationId);
    const typeName = pascal(operation.operationId);
    const fileName = `${functionName}.ts`;
    const source = `// Generated by @kevinmichaelchen/distilled. DO NOT EDIT.\n` +
      `import { Effect } from "effect";\n` +
      `import { DistilledClient, type OperationInput, type OperationOutput, type RuntimeOperationInput } from "${packageImport}";\n` +
      `import type { operations } from "../openapi";\n\n` +
      `type Operation = operations[${JSON.stringify(operation.operationId)}];\n` +
      `export type ${typeName}Input = OperationInput<Operation>;\n` +
      `export type ${typeName}Output = OperationOutput<Operation>;\n\n` +
      `export const ${functionName} = (input: ${typeName}Input) => {\n` +
      `  const runtime = input as RuntimeOperationInput;\n` +
      `  return Effect.flatMap(DistilledClient, (client) =>\n` +
      `    client.request<${typeName}Output>({\n` +
      `      method: ${JSON.stringify(operation.method)},\n` +
      `      path: ${JSON.stringify(operation.path)},\n` +
      `      pathParams: runtime.parameters?.path,\n` +
      `      query: runtime.parameters?.query,\n` +
      `      headers: runtime.parameters?.header,\n` +
      `      body: runtime.body,\n` +
      `    }),\n` +
      `  );\n` +
      `};\n`;
    await writeFile(join(options.outputDir, "operations", fileName), source);
    exports.push(`export * from "./${basename(fileName, ".ts")}";`);
    manifest.push(operation);
  }

  await writeFile(join(options.outputDir, "operations", "index.ts"), `${exports.join("\n")}\n`);
  await writeFile(
    join(options.outputDir, "manifest.json"),
    `${JSON.stringify({ operationCount: operations.length, operations: manifest }, null, 2)}\n`,
  );
  return { operationCount: operations.length };
};
